name: Call API every 15 minutes

on:
  workflow_dispatch:

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "date=$(date -u +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Call API with date parameter
        run: |
          echo "Calling API with date: ${{ env.date }}"
          curl -X POST "https://ufvmenudataprocessor.azurewebsites.net/api/get-ufv-menu?date=${{ env.date }}"
